# Docker Compose override file for local development
# This file is automatically loaded by docker-compose and overrides settings in docker-compose.yml

version: '3.8'

services:
  mcp-webscraper-dev:
    # Enable file watching for hot reload
    volumes:
      - .:/app
      - /app/node_modules
      - /app/cache
      - /app/logs
    environment:
      # Development-specific environment variables
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - CACHE_ENABLE_DISK=true
      - ENABLE_METRICS=true
      - SEARCH_PROVIDER=duckduckgo  # Use DuckDuckGo for development (no API key needed)
    # Enable hot reload
    command: ["npm", "run", "dev"]
    # Bind mount for faster development
    stdin_open: true
    tty: true

  # Override production settings for local testing
  mcp-webscraper-prod:
    environment:
      # Use development-friendly settings
      - LOG_LEVEL=debug
      - SEARCH_PROVIDER=duckduckgo
    # Expose more ports for debugging
    ports:
      - "3001:3000"
      - "9229:9229"  # Debug port